# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='history',
            field=models.TextField(default=b' '),
        ),
        migrations.AddField(
            model_name='users',
            name='is_apply_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_apply_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.IntegerField(default=0),
        ),
    ]
