# Generated by Django 3.1.1 on 2020-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=30)),
                ('borrow_from', models.DateTimeField(blank=True)),
                ('borrow_til', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='history_e',
            field=models.ManyToManyField(blank=True, to='Users.HIS'),
        ),
        migrations.AddField(
            model_name='users',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, to='Users.LIST'),
        ),
    ]
