# Generated by Django 3.1.1 on 2020-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rent_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='rent_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
