# Generated by Django 3.1.1 on 2020-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200904_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='apply_equip_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='reason_a',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='users',
            name='userid',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='history',
            field=models.TextField(default=' '),
        ),
    ]
