# Generated by Django 3.1.1 on 2020-09-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200907_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='noti_count',
            field=models.IntegerField(default=0),
        ),
    ]
