# Generated by Django 3.1.1 on 2020-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=300)),
                ('grade', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('rent_start', models.CharField(default=' ', max_length=30)),
                ('rent_exp', models.CharField(default=' ', max_length=30)),
                ('reason', models.CharField(default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('rent_start', models.DateTimeField(blank=True, null=True)),
                ('rent_exp', models.DateTimeField(blank=True, null=True)),
                ('apply_succes', models.BooleanField(default=False)),
                ('reason', models.CharField(default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('rent_start', models.DateTimeField(blank=True, null=True)),
                ('rent_exp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_rent', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('provider_id', models.CharField(default='0', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('apply_num', models.IntegerField(default=0)),
                ('is_apply', models.BooleanField(default=False)),
                ('reason', models.CharField(default='', max_length=200)),
                ('rent_user_name', models.CharField(default='', max_length=50)),
                ('rent_user_id', models.IntegerField(default=0)),
                ('apply_pending_list', models.ManyToManyField(blank=True, to='Equipment.Pending')),
                ('grade_list', models.ManyToManyField(blank=True, to='Equipment.GRADE')),
                ('history_list', models.ManyToManyField(blank=True, to='Equipment.HIS')),
                ('waiting_list', models.ManyToManyField(blank=True, to='Equipment.LIST')),
            ],
        ),
    ]
