# Generated by Django 3.1.1 on 2020-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='is_gelai',
            field=models.IntegerField(default=0),
        ),
    ]
