# Generated by Django 3.1.1 on 2020-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_rent', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('provider_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_apply', models.BooleanField(default=False)),
                ('reason', models.CharField(default='', max_length=200)),
                ('rent_start', models.DateTimeField(blank=True, null=True)),
                ('rent_exp', models.DateTimeField(blank=True, null=True)),
                ('rent_user_name', models.CharField(default='', max_length=50)),
                ('rent_user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
