# Generated by Django 3.1.1 on 2020-09-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='name',
            new_name='equip_id',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='list',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
