# Generated by Django 3.1.1 on 2020-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_auto_20200907_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equip',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equip',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equip',
            name='reason',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='equip',
            name='rent_user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
