# Generated by Django 3.1.1 on 2020-09-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_auto_20200909_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='rent_exp',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='rent_start',
        ),
        migrations.RemoveField(
            model_name='list',
            name='equip_id',
        ),
        migrations.RemoveField(
            model_name='list',
            name='time',
        ),
        migrations.AddField(
            model_name='list',
            name='rent_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='rent_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='user_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
