# Generated by Django 3.1.1 on 2020-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0003_auto_20200909_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=300)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('rent_start', models.DateTimeField(blank=True, null=True)),
                ('rent_exp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='grade_list',
            field=models.ManyToManyField(blank=True, to='Equipment.GRADE'),
        ),
        migrations.AddField(
            model_name='equip',
            name='history_list',
            field=models.ManyToManyField(blank=True, to='Equipment.HIS'),
        ),
    ]
