# Generated by Django 3.1.1 on 2020-09-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0004_auto_20200909_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('rent_start', models.DateTimeField(blank=True, null=True)),
                ('rent_exp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='apply_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='apply_succes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='reason',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equip',
            name='apply_pending_list',
            field=models.ManyToManyField(blank=True, to='Equipment.Pending'),
        ),
    ]
