# Generated by Django 3.1.1 on 2020-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=300)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=30)),
                ('equip_id', models.IntegerField(default=0)),
                ('borrow_from', models.CharField(default=' ', max_length=30)),
                ('borrow_till', models.CharField(default=' ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('userid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(default='1234', max_length=300)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.IntegerField(default=0)),
                ('is_rent', models.BooleanField(default=False)),
                ('is_apply_a', models.BooleanField(default=False)),
                ('is_apply_b', models.BooleanField(default=False)),
                ('history', models.TextField(default=' ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_a', models.CharField(default='', max_length=3000)),
                ('apply_equip_id', models.IntegerField(default=0)),
                ('apply_equip_name', models.CharField(default=' ', max_length=100)),
                ('noti_count', models.IntegerField(default=0)),
                ('rent_start', models.CharField(default=' ', max_length=100)),
                ('rent_end', models.CharField(default=' ', max_length=100)),
                ('rent_status', models.IntegerField(default=0)),
                ('grade_list', models.ManyToManyField(blank=True, to='Users.GRADE')),
                ('history_e', models.ManyToManyField(blank=True, to='Users.HIS')),
                ('waiting_list', models.ManyToManyField(blank=True, to='Users.LIST')),
            ],
        ),
    ]
