# Generated by Django 3.1.1 on 2020-09-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rent_end',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='rent_start',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
