# Generated by Django 3.1.1 on 2020-09-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200912_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='his',
            old_name='name',
            new_name='equip_name',
        ),
        migrations.RemoveField(
            model_name='his',
            name='userid',
        ),
        migrations.AddField(
            model_name='his',
            name='equip_id',
            field=models.IntegerField(default=0),
        ),
    ]
